routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', 'DishController@index');

Route::get('/home', 'HomeController@index');
Route::resource('table', 'TableController');
Route::get('saulius', 'HomeController@saulius');

Route::resource('dishes', 'DishController');

Route::resource('orders', 'OrderController');

Route::get('checkout', 'OrderController@checkout')->name('cart.checkout');

Route::post('cart', 'OrderController@addToCart')->name('cart.add');
Route::delete('cart', 'OrderController@clearCart')->name('cart.clear');
Route::get('cart/delete/{id}' ,'OrderController@deleteLine')->name('cart.delete_line');
Route::post('cart/reservation', 'CheckoutController@store')->name('checkout.store');
Route::get('cart/confirm', 'CheckoutController@confirm')->name('checkout.confirm');

Route::get('/profile', 'UserController@user')->name('profile.edit');
Route::get('/profile', 'UserController@profile')->name('profile')->middleware('auth');
Route::put('/profile', 'UserController@update')->name('profile.update')->middleware('auth');

Route::resource('contact', 'ContactController');

Route::delete('orders/line/{id}/destroy', 'OrderController@destroyLine')->name('orders.line_destroy');

Route::put('add/dish', 'OrderController@addDishToOrder')->name('add.dist_to_order');

//user
Route::resource('users',  'UserController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'surname', 'date', 'phone', 'email', 'password', 'address', 'city', 'zip', 'country',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function orders(){
      return $this->hasMany('App\Order');
    }

    public function isAdmin()
    {
      return $this->type == 'admin';
    }

    public function getCoutryName()
    {
      $countries = [
        "LT" => 'Lietuva',
      ];

      return isset($countries[$this->country]) ? $countries[$this->country] : $this->country;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Order;

class UserController extends Controller
{

  public function __construct(){
    $this->middleware('auth.Admin');
  }


  public function profile()
  {
      $user = \Auth::user();
      $title = 'Update profile';
      return view('auth.register', compact('user', 'title'));
  }

  public function update(Request $request)
  {
      $user = \Auth::user();

      $user->name = $request->name;
      $user->surname = $request->surname;
      $user->date = $request->date;
      $user->phone = $request->phone;
      $user->city = $request->city;
      $user->zip = $request->zip;
      $user->country = $request->country;
      $user->save();

      return redirect()->route('dishes.index')->with('message', [
          'text' => 'Profile updated!',
          'type' => 'success'
      ]);
  }

  public function index()
  {
    $users = User::all();
    return view('user.index' , compact('users'));
  }

  public function show(User $user)
  {
    $user = User::find($user);
    return view('user.show', compact('user'));
  }

  public function edit(User $user){
    //
  }

  public function destroy(User $user)
  {
    $user->delete();

    return redirect()->route('users.index');
  }
}

resources/views/user/form.blade.php
@extends('layouts.app')

@section('content')















  @endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<h1>List of users</h1>

	<table class="table table-hover">
		<thead>
			<tr>
				<td>#</td>
				<td>Name</td>
				<td>Type</td>
				<td>Email</td>
				<td>Orders</td>
				<td></td>
			</tr>
		</thead>
		<tbody>
		@foreach($users as $index => $user)
			<tr>
				<td>{{ $index + 1 }}</td>
				<td>{{ $user->name }}</td>
				<td><span class="badge">{{ $user->type }}</span></td>
				<td>{{ $user->email }}</td>
				<td>{{ count($user->orders) }}</td>
				<td><a href="{{ route('users.show', $user->id) }}">View</a></td>
			</tr>
		@endforeach
		</tbody>
	</table>
</div>
@endsection

resources/views/user/show.blade.php
@extends('layouts.app')

@section('content')



<h1><span>Name: {{ $user->name }}</span>
  <td><a href="{{ route('users.edit', ['id' => $user->id]) }}" class="btn btn-warning pull-right">Edit</a></td>
</h1>
<br>
<div class="row">
  <div class="col-md-6">
    <span>Surname: {{ $user->surname }}</span><br>
    <span>Email: {{ $user->email }}</span><br>
    <span>Date: {{ $user->date }}</span><br>
    <span>Phone: {{ $user->phone }}</span><br>
    <span>type: {{ $user->type }}</span><br>
  </div>
  <div class="col-md-6">
    <span>Address: {{ $user->address }}</span><br>
    <span>City: {{ $user->city }}</span><br>
    <span>zip: {{ $user->zip }}</span><br>
    <span>country: {{ $user->getCoutryName() }}</span><br>
  </div>
</div>
<ul class="nav nav-tabs">
  <li class="active"><a href="#">Orders</a></li>
</ul>
<div class="table-responsive">
<table id="table-with-sorting" class="table">
  <thead>
    <tr>
      <th>Order id</th>
      <th>Table name  </th>
      <th>Phone</th>
      <th>Total price</th>
      <th>Dishes count</th>
      <th>Email</th>
      <th>Reservation date</th>
      <th>Reservation time</th>
    </tr>
  </thead>
  <tbody>
    @foreach ($user->orders as $order)

    <tr class="{{ $order->getReservationClass() }}">
      <td> {{ $order->id }} </td>
      <td> {{ $order->table->title }} </td>
      <td> {{ $order->contact_phone }} </td>
       <td>{{ $order->total }}€</td>
      <td>{{ $order->order_lines->sum('quantity') }}</td>
      <td> {{ $order->email }} </td>
      <td> {{ $order->reservation_date }} </td>
      <td> {{ $order->reservation_time }} </td>
      <td>
          {!! Form::open(['route' => ['orders.destroy', $order->id], 'method' => 'delete'])!!}
              <a href="{{ route('orders.show', $order) }}" class="btn btn-default"><span class="glyphicon glyphicon-eye-open"></span> Peržiūra</a>
              {!! Form::hidden('redirect_url', route('users.show', $user)) !!}
              {!! Form::submit('Delete' , ['class' => 'btn btn-danger'])!!}
          {!! Form::close() !!}
      </td>
    </tr>
  @endforeach
  </tbody>
</table>
</div>

{{--
@if(Auth::user() && Auth::user()->isAdmin())


  {!! Form::open(['route' => ['table.destroy', $table->id], 'method' => 'delete', 'class' => 'pull-right'])  !!}
  {!! Form::submit('Delete', ['class'=>'btn btn-danger']) !!}
  {!! Form::close() !!}

@endif --}}



  @endsection