routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', 'DishController@index');

Route::get('/home', 'HomeController@index');
Route::resource('table', 'TableController');
Route::get('saulius', 'HomeController@saulius');

Route::resource('dishes', 'DishController');

Route::resource('orders', 'OrderController');

Route::get('checkout', 'OrderController@checkout')->name('cart.checkout');

Route::post('cart', 'OrderController@addToCart')->name('cart.add');
Route::delete('cart', 'OrderController@clearCart')->name('cart.clear');
Route::get('cart/delete/{id}' ,'OrderController@deleteLine')->name('cart.delete_line');
Route::post('cart/reservation', 'CheckoutController@store')->name('checkout.store');
Route::get('cart/confirm', 'CheckoutController@confirm')->name('checkout.confirm');

Route::get('/profile', 'UserController@user')->name('profile.edit');
Route::get('/profile', 'UserController@profile')->name('profile')->middleware('auth');
Route::put('/profile', 'UserController@update')->name('profile.update')->middleware('auth');

Route::resource('contact', 'ContactController');

Route::delete('orders/line/{id}/destroy', 'OrderController@destroyLine')->name('orders.line_destroy');

Route::put('add/dish', 'OrderController@addDishToOrder')->name('add.dist_to_order');

//user
Route::resource('users',  'UserController');

app/Dish.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Dish extends Model
{
  protected $fillable = [
    'title',
    'photo',
    'description',
    'price',
    'netto_price',
    'quantity',
  ];

      public function getFormattedPriceAttribute($value)
      {
         return number_format($this->price / 1, 2);
      }
      public function getFormattedNetoPriceAttribute($value)
      {
         return number_format($this->netto_price / 100, 2);
      }

      public function order_lines()
     {
       return $this->hasMany('App\OrderLine');
     }

     public function getWithoutVat()
     {
         return \App\Price::getWithoutVat($this->FormattedPrice);
     }

     public function getVat()
     {
         return $this->FormattedPrice - $this->getWithoutVat();
     }
  }

app/Http/Controllers/DishController.php
<?php

namespace App\Http\Controllers;

use App\Dish;
use Illuminate\Http\Request;

class DishController extends Controller
{

  public function __construct(){
    $this->middleware('auth.Admin')->except(['index', 'show']);
  }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dishes = Dish::all();
        return view('dish.index' , compact('dishes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dish.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      if ($request->hasFile('photo')) {
          $file = $request->file('photo');
          $file->store('public');
          $request->photo = $file->hashName();
        }

        Dish::create([
          'title' => $request->get('title'),
          'photo' => $request->photo,
          'price' => $request->get('price'),
          'netto_price' => $request->get('netto_price'),
          'quantity' => $request->get('quantity'),
          'description' => $request->get('description'),
        ]);

        return redirect()->route('dishes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Dish  $dish
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $dish = Dish::find($id);
      return view('dish.show', compact('dish'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Dish  $dish
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $dish = Dish::find($id);
        return view('dish.form', compact('dish'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Dish  $dish
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Dish $dish)
    {

      if ($request->hasFile('photo')) {
          $file = $request->file('photo');
          $file->store('public');
          $request->photo = $file->hashName();
        }

        $dish->update([
          'title' => $request->get('title'),
          'photo' => $request->photo,
          'price' => $request->get('price'),
          'netto_price'=> $request->get('netto_price'),
          'quantity' => $request->get('quantity'),
          'description' => $request->get('description'),
        ]);
        return redirect()->route('dishes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Dish  $dish
     * @return \Illuminate\Http\Response
     */
    public function destroy(Dish $dish)
    {
        $dish->delete();

        return redirect()->route('dishes.index');
    }
}

resources/views/dish/form.blade.php
@extends('layouts.app')

@section('content')

@if(isset($dish))
  {!! Form::model($dish, ['route' => ['dishes.update', $dish->id], 'method' => 'put', 'files' => true])  !!}
@else
  {!! Form::open(['route' => ['dishes.store'], 'method' => 'post', 'files' => true])  !!}
@endif


<div class="form-group">
  {!! Form::label('title', 'Title'); !!}
	{!!  Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'TITLE']) !!}
</div>

<div class="form-group">
	{!! Form::file('photo', null) !!}
</div>

{{-- <div class="form-group">
  {!! Form::label('photo', 'Photo'); !!}
	{!!  Form::text('photo', null, ['class' => 'form-control']) !!}
</div> --}}

<div class="form-group">
	{!! Form::label('price', 'Price'); !!}
	{!!  Form::text('price', null, ['class' =>'form-control']) !!}
</div>

<div class="form-group">
	{!! Form::label('netto_price', 'Netto price'); !!}
	{!!  Form::text('netto_price', null, ['class' =>'form-control']) !!}
</div>

<div class="form-group">
	{!! Form::label('quantity', 'Quantity'); !!}
	{!!  Form::number('quantity', null, ['class' =>'form-control']) !!}
</div>

<div class="form-group">
	{!! Form::label('desciption', 'Desciption'); !!}
	{!!  Form::textarea('description', null, ['class' => 'form-control', 'placeholder' => 'Desciption']) !!}
</div>

{!! Form::submit('Save',['class' => 'btn btn-primary']) !!}


{{ Form::close() }}

@endsection

resources/views/dish/index.blade.php
@extends('layouts.app')

@section('content')

  @foreach ($dishes->chunk(3) as $chunk)
    <div class="row">
      @foreach ($chunk as $dish)
        <div class="col-md-4">
          <div class="thumbnail">

            <a href="{{ route('dishes.show', $dish->id) }}"><img src="{{ asset('/storage/' . $dish->photo) }}" alt="{{ $dish->title }}" class="img-responsive"></a>
            <div class="caption">
              <h3>{{ $dish->title }}</h3>
              <p>{{ $dish->description }}</p>
              <p>
                Kaina: {{ $dish->price }}€
                Net kaina: {{ $dish->netto_price }}€
                Kiekis: {{ $dish->quantity }}vnt.
              </div>
              <a href="#" class="btn btn-warning add-to-cart" data-id="{{$dish->id}}">Add to cart</a>
            </div>
          </div>
        @endforeach
      </div>
    @endforeach

  @endsection

resources/views/dish/show.blade.php
@extends('layouts.app')

@section('content')




  <h1>{{ $dish->title}}</h1>


  <img src="{{ asset('/storage/' . $dish->photo) }}" alt="{{ $dish->title }}" class="img-responsive">

  <p>{{ $dish->description}}</p>


  <ul>
  	<li>Kaina: {{ $dish->price }}€ </li>
  </ul>


  <br>
@if(Auth::user() && Auth::user()->isAdmin())
  <a href="{{ route('dishes.edit', $dish->id) }}" class="btn btn-primary">Edit</a>


{!! Form::open(['route' => ['dishes.destroy', $dish->id], 'method' => 'delete', 'class' => 'btn-group'])  !!}
{!! Form::submit('Delete', ['class'=>'btn btn-danger']) !!}
{!! Form::close() !!}

@endif






@endsection