routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', 'DishController@index');

Route::get('/home', 'HomeController@index');
Route::resource('table', 'TableController');
Route::get('saulius', 'HomeController@saulius');

Route::resource('dishes', 'DishController');

Route::resource('orders', 'OrderController');

Route::get('checkout', 'OrderController@checkout')->name('cart.checkout');

Route::post('cart', 'OrderController@addToCart')->name('cart.add');
Route::delete('cart', 'OrderController@clearCart')->name('cart.clear');
Route::get('cart/delete/{id}' ,'OrderController@deleteLine')->name('cart.delete_line');
Route::post('cart/reservation', 'CheckoutController@store')->name('checkout.store');
Route::get('cart/confirm', 'CheckoutController@confirm')->name('checkout.confirm');

Route::get('/profile', 'UserController@user')->name('profile.edit');
Route::get('/profile', 'UserController@profile')->name('profile')->middleware('auth');
Route::put('/profile', 'UserController@update')->name('profile.update')->middleware('auth');

Route::resource('contact', 'ContactController');

Route::delete('orders/line/{id}/destroy', 'OrderController@destroyLine')->name('orders.line_destroy');

Route::put('add/dish', 'OrderController@addDishToOrder')->name('add.dist_to_order');

//user
Route::resource('users',  'UserController');

app/Order.php
<?php

namespace App;


use Illuminate\Database\Eloquent\Model;
use App\OrderLine;
use Carbon\Carbon;

class Order extends Model
{
  protected $fillable = [
    'name',
    'email',
    'total',
    'date',
    'user_id',
    'contact_phone',
    'number_of_persons',
    'date',
    'reservation_time',
    'reservation_date',
    'table_id',
  ];

  public function order_lines()
  {
    return $this->hasMany('App\OrderLine');
  }

  public function user(){
    return $this->belongsTo('App\User');
  }
  public function table(){
    return $this->belongsTo('App\Table');
  }
public function getReservationClass()
{
  // Sviesaforas rodomas tik tada kai ziuri administratorius
  if (\Auth::check() && \Auth::user()->isAdmin()) {
    $date = Carbon::parse($this->reservation_date);

    if ($date->isToday()) {
      // yra siandien
      return 'danger';

    }else if ($date->isTomorrow()){
      //rytoj
      return 'warning';

    }else if ($date->isPast()) {
      //vakar
      return ' success';

    }else {
      //Ateitis po rytojaus
      return 'default';
    }
  }

  return '';
}

    public function getWithoutVat()
    {
        return \App\Price::getWithoutVat($this->total);
    }

    public function getVat()
    {
        return $this->total - $this->getWithoutVat();
    }

}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Order;
use App\Dish;
use App\Table;
use App\OrderLine;
use Illuminate\Http\Request;
use App\Price;

class OrderController extends Controller
{

  public function __construct(){
    //auth.admin gali viska, iskyrus visi kiti except([...])
    $this->middleware('auth.Admin')->except(['index', 'show','addToCart', 'clearCart', 'deleteLine', 'checkout', 'store']);
    //auth gali tai ka leido auth.Admin, o non-register gali tai kas yra addToCart
    $this->middleware('auth')->except(['addToCart', 'clearCart', 'deleteLine', 'checkout']);
  }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      if(\Auth::user()->isAdmin()){
        $orders = Order::orderBy('date', 'desc')->get();
      }else{
        // $orders = Order::where('user_id', \Auth::user()->id)->get();
        $orders = \Auth::user()->orders()->orderBy('date', 'desc')->get();
      }
      // dump($orders);
      // return view('order.index' , ['orders' => $orders]);
        return view('order.index' , compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (session('cart.total')) {
          return view('order.form');
        }else{
          return redirect()->route('dishes.index');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      // $order = Order::create([
      //   'name' => $request->name,
      //   'email' => $request->email,
      //   'total' => session('cart.total'),
      //   'date' => \Carbon\Carbon::now(),
      //   'user_id'=>\Auth::user()->id,
      // ]);

      $order = Order::create([
        'name' => session('cart.reservation_info')['name'],
        'email' => session('cart.reservation_info')['email'],
        'contact_phone' => session('cart.reservation_info')['contact_phone'],
        'number_of_persons' => session('cart.reservation_info')['number_of_persons'],
        'table_id' => session('cart.reservation_info')['table_id'],
        'date' => \Carbon\Carbon::now(),
        'reservation_date' => session('cart.reservation_info')['reservation_date'],
        'reservation_time' => session('cart.reservation_info')['reservation_time'],
        'total' => session('cart.total'),
        'user_id'=>\Auth::user()->id,
      ]);

      foreach (session('cart.items') as $item) {
        OrderLine::create([
          'order_id' => $order->id,
          'dish_id' => $item['id'],
          'quantity'=> $item['quantity'],
          'total' => $item['total']
        ]);
      }

      $this->clearCart();

      return redirect()->route('contact.index')->with('message', [
        'text' => 'Uzsakymas ivykdytas',
        'type' => 'success'
      ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $order = Order::find($id);
      return view('order.show', compact('order'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $table = Table::find(session('cart.reservation_info.table_id'));
      $dishes = Dish::all();
      $order = Order::find($id);
      return view('order.form', compact('order','table','dishes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [

              'name' => 'required|max:255',
              'email' => 'required|email|max:255',
              'number_of_persons' => 'required|numeric|between:0,15',
              'reservation_date' => 'required|max:255',
              'reservation_time' => 'required|max:255',

           ]);

      Order::find($id)->update($request->all());
      return redirect()->route('orders.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order, Request $request)
    {
      $order->order_lines()->delete();
      $order->delete();

            if ($request->has('redirect_url')) {
            return redirect()->to($request->redirect_url);

             }

      return redirect()->route('orders.index');
    }

    public function destroyLine($id)
    {
        $line = OrderLine::findOrFail($id);

        /**
         * pakoreguoja bendrą orderio sumą
         */
        $line->order->total -= $line->total;
        $line->order->save();

        $line->delete();

        return redirect()->route('orders.edit', $line->order->id);
    }

    public function addToCart(Request $request){
            // session(['cart.items'=> [] ]);
            $dish_id = $request->id;
            $dish = Dish::find($dish_id);
            $product = [
            'id' => $dish->id,
            'photo' => $dish->photo,
            'title' => $dish->title,
            'quantity' => 1,
            'netto_price' => $dish->netto_price,
            'price' => $dish->price,
            'total' =>$dish->price,
            'without_vat' =>$dish->getWithoutVat(),
            'vat' =>$dish->getVat()
            ];
            $items = session('cart.items');
            $existing = false;

            if ($items && count($items) > 0) {

                foreach($items as $index => $item) {
                    if($item['id'] == $dish_id) {
                        $items[$index]['quantity'] = $item['quantity'] + $product['quantity'];
                        $items[$index]['total'] = $items[$index]['quantity'] * $dish->FormattedPrice;

                        $items[$index]['without_vat'] = $items[$index]['quantity'] * $dish->getWithoutVat();
                        $items[$index]['vat'] = $items[$index]['quantity'] * $dish->getVat();
                        $existing = true;
                    }

                }
            }
            if(! $existing){
                session()->push('cart.items', $product);
            } else {
                session(['cart.items'=> $items]);
            }

            $this->calculateCartTotals();

            return session('cart');
        }

    public function clearCart(){
      session([
        'cart.items' =>[],
        'cart.total_without_vat' => 0,
        'cart.total_vat' => 0,
        'cart.total' => 0,
      ]);
    }

    public function deleteLine(Request $request) {
            $id = $request->id;
            $items = session('cart.items');
            $total = session('cart.total');

            foreach($items as $index =>$item){
                if($item['id'] == $id){
                    $total -= $item['total'];
                    unset($items[$index]);
                    break;
                }
            }
            session([
                    'cart.items' => $items
            ]);

            $this->calculateCartTotals();

            return redirect()->route('cart.checkout');
        }

    public function checkout() {
            $tables = Table::all()->pluck('title', 'id');

            return view('order.checkout', compact('tables'));
    }

    private function calculateCartTotals() {
            $items = session('cart.items');
            $grand_total = 0;

            foreach($items as $item) {
                $grand_total = $grand_total + $item['total'];
            }

            $withoutVat = Price::getWithoutVat($grand_total);
            $vat = Price::getVat($grand_total);

            session([
                'cart.total_without_vat' => $withoutVat,
                'cart.total_vat' => $vat,
                'cart.total' => $grand_total
            ]);
        }

    private function addDishToOrder(Request $request, Dish $dish)
    {

    }
}

resources/views/order/checkout.blade.php
@extends('layouts.app')

@section('content')

  @if(session('cart.items') && count(session('cart.items')) > 0)
        <table class="table table-bordered text-center">
          <thead>
            <tr>
              <th>Photo</th>
              <th>Pavadinimas</th>
              <th>Kiekis</th>
              <th>Vnt. Kaina</th>
              <th>PVM</th>
              <th>Viso be PVM</th>
              <th>Viso</th>
            </tr>
          </thead>
          <tbody>
            @foreach(session('cart.items') as $item)
            <tr>
              <td><img src="{{ asset('/storage/' . $item['photo']) }}" alt="{{ $item['title'] }}" class="img-responsive center-block cartImage" style="width: 200px"></td>
                <td><span class="cartImage">{{ $item['title']}}</span></td>
              </td>
              <td>{{ $item['quantity']}}</td>
              <td>{{ $item['price']}}</td>
              <td>{{ $item['vat'] }}&euro;</td>
              <td>{{ $item['without_vat'] }}&euro;</td>
              <td>{{ $item['total']}} &euro;</td>
              <td><a href="{{ route('cart.delete_line', ['id' => $item['id']]) }}"><i class="fa fa-trash" aria-hidden="true"></i></a></td>
            </tr>
            @endforeach
          </tbody>
          <tfoot>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>{{ session('cart.total_vat') ?: '0' }} &euro;</td>
            <td>{{ session('cart.total_without_vat') ?: '0' }} &euro;</td>
            <td> {{ session('cart.total') ?: '0' }} &euro;</td>
          </tfoot>

        </table>

<h1>Reservation info</h1>
{!! Form::open(['route' => 'checkout.store', 'method' => 'post']) !!}

<div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">

  {!! Form::label('name', 'Contact Name'); !!}
  {!! Form::text('name', Auth::user() ? Auth::user()->name : null , ['class' => 'form-control', 'placeholder' => 'Name']) !!}

  @if ($errors->has('name'))
  <span class="help-block">
      <strong>{{ $errors->first('name') }}</strong>
  </span>
  @endif
</div>

<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
  {!! Form::label('email', 'Email'); !!}
	{!!  Form::text('email', Auth::user() ? Auth::user()->email : null, ['class' => 'form-control', 'placeholder' => 'Emailas']) !!}

  @if ($errors->has('email'))
  <span class="help-block">
      <strong>{{ $errors->first('email') }}</strong>
  </span>
  @endif
</div>

<div class="form-group{{ $errors->has('contact_phone') ? ' has-error' : '' }}">
  {!! Form::label('contact_phone', 'Contact phone number'); !!}
  {!!  Form::text('contact_phone', Auth::user() ? Auth::user()->phone : null, ['class' => 'form-control', 'placeholder' => 'number']) !!}
  @if ($errors->has('contact_phone'))
  <span class="help-block">
      <strong>{{ $errors->first('contact_phone') }}</strong>
  </span>
  @endif
</div>

<div class="form-group{{ $errors->has('number_of_persons') ? ' has-error' : '' }}">
  {!! Form::label('number_of_persons', 'Person Number'); !!}
  {!! Form::number('number_of_persons', 1 ,['class' => 'form-control','min' => 1,'max' => 10]) ; !!}
  @if ($errors->has('number_of_persons'))
  <span class="help-block">
      <strong>{{ $errors->first('number_of_persons') }}</strong>
  </span>
  @endif
</div>

<div class="form-group{{ $errors->has('table_id') ? ' has-error' : '' }}">
  {!! Form::label('table_id', 'Select table'); !!}
  {!! Form::select('table_id', $tables, null, ['class' => 'form-control']) !!}
  @if ($errors->has('table_id'))
  <span class="help-block">
      <strong>{{ $errors->first('table_id') }}</strong>
  </span>
  @endif
</div>

<div class="form-group{{ $errors->has('reservation_date') ? ' has-error' : '' }}">
  {!! Form::label('reservation_date', 'Reservation date'); !!}
  {!!  Form::date('reservation_date', Carbon\Carbon::now(), ['class' => 'form-control']) !!}
  @if ($errors->has('reservation_date'))
  <span class="help-block">
      <strong>{{ $errors->first('name') }}</strong>
  </span>
  @endif
</div>

<div class="form-group{{ $errors->has('reservation_time') ? ' has-error' : '' }}">
  {!! Form::label('reservation_time', 'Reservation time'); !!}
  {!!  Form::time('reservation_time', Carbon\Carbon::now()->toTimeString(), ['class' => 'form-control']) !!}
  @if ($errors->has('reservation_time'))
  <span class="help-block">
      <strong>{{ $errors->first('reservation_time') }}</strong>
  </span>
  @endif
</div>

    {!! Form::submit('Sukurti rezervacija',['class' => 'btn btn-warning pull-right']) !!}

{!! Form::close() !!}

        {{-- <a href="{{ route('orders.create') }}" class="btn btn-danger pull-right">Sukurti rezervacija</a> --}}
        {{-- <a href="{{ route('saveToSession') }}" class="btn btn-warning pull-right">Sukurti rezervacija</a> --}}
@else
  <h1><center>Cart is empty</center></h1>

@endif
@endsection

resources/views/order/confirm.blade.php
@extends('layouts.app')

@section('content')
    <h1>Table resevation confirmation</h1>

    <ul>
        <li>Name: {{ session('cart.reservation_info.name') }}</li>
        <li>Email: {{ session('cart.reservation_info.email') }}</li>
        <li>Kontaktinis telefonas: {{ session('cart.reservation_info.contact_phone') }}</li>
        <li>Asmenu skaicius: {{ session('cart.reservation_info.number_of_persons') }}</li>
        <li>Staliukas: {{ $table->title }}</li>
        <li>Data: {{ session('cart.reservation_info.reservation_date') }}</li>
        <li>Laikas: {{ session('cart.reservation_info.reservation_time') }}</li>
    </ul>

    {!! Form::open(['route' => ['orders.store'], 'method' => 'post'])!!}
        {!! Form::submit('Confirm' , ['class' => 'btn btn-success'])!!}
    {!! Form::close() !!}
@endsection

resources/views/order/form.blade.php
@extends('layouts.app')

@section('content')

  @if(isset($order))
    {!! Form::model($order, ['route' => ['orders.update', $order->id], 'method' => 'put', 'files' => true])  !!}
  @else
    {!! Form::open(['route' => ['orders.store'], 'method' => 'post', 'files' => true])  !!}
  @endif

<div class="form-group">
  {!! Form::label('name', 'Vardas'); !!}
	{!!  Form::text('name', isset($order) ? $order->name : Auth::user()->name, ['class' => 'form-control', 'placeholder' => 'Name']) !!}
</div>

<div class="form-group">
  {!! Form::label('email', 'Email'); !!}
	{!!  Form::text('email', isset($order) ? $order->email : Auth::user()->email, ['class' => 'form-control', 'placeholder' => 'Emailas']) !!}
</div>

<div class="form-group">
  {!! Form::label('number_of_persons', 'Number of persons'); !!}
	{!!  Form::text('number_of_persons', null, ['class' => 'form-control', 'placeholder' => 'Number of persons']) !!}
</div>

<div class="form-group">
  {!! Form::label('reservation_date', 'Reservation date'); !!}
	{!!  Form::text('reservation_date', null, ['class' => 'form-control', 'placeholder' => 'reservation_date']) !!}
</div>

<div class="form-group">
  {!! Form::label('reservation_time', 'Reservation time'); !!}
	{!!  Form::text('reservation_time', null, ['class' => 'form-control', 'placeholder' => 'reservation_time']) !!}
</div>

{{-- <div class="form-group">
  {!! Form::label('table_id', 'Select table'); !!}
	{!!  Form::select('table_id', $table, null, ['class' => 'form-control', 'placeholder' => 'reservation_time']) !!}
</div> --}}

{!! Form::submit('Update',['class' => 'btn btn-warning']) !!}

{{ Form::close() }}
<br>
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<table class="table">
              <thead>
                <tr>
                  <th>Photo</th>
                  <th>Order id</th>
                  <th>Table name  </th>
                  <th>Dishes count</th>
                  <th>Price</th>
                  <th></th>
                </tr>
              </thead>

              @if(count($order->order_lines()) > 0)
              <tbody>
                @foreach($order->order_lines as $item)
                <tr>
                  <td><img style="max-width: 50px;" src="{{ asset('/storage/' . $item->dish->photo) }}" alt=""> {{ $item->dish->title }}</td>
                  <td> {{ $order->id }} </td>
                  <td> {{ $order->table->title }} </td>
                  <td> {{ $item->quantity }}</td>
                  <td> {{ $item ->total }}€</td>
          					<td>
          						{!! Form::open(['route' => ['orders.line_destroy', $item->id], 'method' => 'delete'])!!}
          							{!! Form::submit('X' , ['class' => 'btn btn-danger'])!!}
          						{!! Form::close() !!}
          					</td>
          				</tr>
          			@endforeach
              </tbody>
              <tfoot>
                <tr>
                  <td colspan="4" class="text-right">Total price:</td>
                  {{-- <td>{{ $order->total }}</td> --}}
                  <td>{{ $order->order_lines->sum('total') }}€</td>
                </tr>
              </tfoot>
              @endif

            </table>


    {!! Form::open(['route' => ['add.dist_to_order', $order->id] 'method' => 'PUT'])  !!}

    <div class="form-group">
      {!! Form::label('dishes', 'Select dishes'); !!}

      <select class="btn btn-primary dropdown-toggle" name="dishes">
        @foreach ($dishes as $dish)
          <option value="{{$dish->id}}">{{$dish->title}}</option>
        @endforeach
      </select>

      <!-- Single button -->
{{-- <div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Select dishes <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    @foreach ($dishes as $dish)
    <li name="{{$dish->id}}"><a href="#">{{$dish->title}}</a></li>
    @endforeach
  </ul>
</div> --}}
    </div>

    {!! Form::submit('Add dish',['class' => 'btn btn-primary']) !!}

    {{ Form::close() }}










@endsection

resources/views/order/index.blade.php
@extends('layouts.app')

@section('content')

<table class="table">

  <thead>
    <tr>
      <th>Uzsakymo pavadinimas</th>
      <th>Vardas</th>
      <th>Kaina</th>
      <th>Email</th>
      <th>Stalelio pavadinimas</th>
      <th>Reservation date</th>
      <th>Rezervacijos laikas</th>
      <th>PVM</th>
      <th>Suma be PVM</th>
    </tr>
  </thead>
<tbody>
  @if(isset($orders) && count($orders) > 0)
    @foreach ($orders as $order)

      <tr class="{{ $order->getReservationClass() }}">

        <td><h3><a href="{{ route('orders.show', $order->id) }}"> Uzsakymas {{$order->name}}</a></h3></td>
        <td>{{$order->name}}</td>
        <td>{{$order->total}}</td>
        <td>{{$order->email}}</td>
        <td>{{$order->table->title }}</td>
        <td>{{$order->reservation_date}}</td>
        <td>{{$order->reservation_time}}</td>
      <td>PVM {{ $order->getVat() }} € </td>
      <td>Suma be PVM: {{ $order->getWithoutVat() }} €</td>
      </tr>
    @endforeach
  @endif
</tbody>
</table>
@endsection

resources/views/order/show.blade.php
  @extends('layouts.app')

@section('content')




  <h1>{{$order->name}}</h1>




  <p>Email:{{ $order->email}}</p>


  <ul>
  	<li>Total: {{ $order->total }}€ </li>
    <li>Date: {{ $order->date }}€ </li>
  </ul>


  <br>
  <table class="table">
  							<thead>
  								<tr>
                    <th>Photo</th>
                    <th>Order id</th>
                    <th>Table name  </th>
                    <th>Phone</th>
                    <th>Dishes count</th>
                    <th>Email</th>
                    <th>Reservation date</th>
                    <th>Reservation time</th>
                    <th>Price</th>
  								</tr>
  							</thead>

  							@if(count($order->order_lines()) > 0)
  							<tbody>
  								@foreach($order->order_lines as $item)
  								<tr>
  									<td><img style="max-width: 50px;" src="{{ asset('/storage/' . $item->dish->photo) }}" alt=""> {{ $item->dish->title }}</td>
                    <td> {{ $order->id }} </td>
                    <td> {{ $order->table->title }} </td>
                    <td> {{ $order->contact_phone }} </td>
                    <td> {{ $item->quantity }}</td>
                    <td> {{ $order->email }} </td>
                    <td> {{ $order->reservation_date }} </td>
                    <td> {{ $order->reservation_time }} </td>
                    <td> {{ $item ->total }}€</td>
  								</tr>
  								@endforeach
  							</tbody>
  							<tfoot>
  								<tr>
  									<td colspan="8" class="text-right">Total price:</td>
  									{{-- <td>{{ $order->total }}</td> --}}
  									<td>{{ $order->order_lines->sum('total') }}€</td>
  								</tr>
  							</tfoot>
  							@endif

  						</table>


@if(Auth::user() && Auth::user()->isAdmin())
  <a href="{{ route('orders.edit', $order->id) }}" class="btn btn-primary">Edit</a>

{!! Form::open(['route' => ['orders.destroy', $order->id], 'method' => 'delete', 'class' => 'btn-group'])  !!}
{!! Form::submit('Delete', ['class'=>'btn btn-danger']) !!}
{!! Form::close() !!}

@endif


@endsection